service: puller

provider:
  name: aws
  runtime: nodejs8.10

functions:
  puller:
    handler: puller.puller
    environment:
      GITHUB_TOKEN: ''
      baseRepoOwner: ''
      repoName: ''
      baseRepoBranch: ''
      headRepoOwner: ''
      headRepoBranch: ''
    events:
      - schedule: rate(1 hour)
